version: '3.8'
services:
  web:
    build: .
    environment:
      - SECRET_KEY_BASE=secret
      - MONGO_URI=mongodb://root:Secret@mongo:27017/url_shortner?authSource=admin
    ports:
    - "8000:8000"
    volumes:
    - .:/opt
    links:
    - mongo
    
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Secret
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
volumes:
  mongo-data:
  mongo-configdb: